services:
  backend:
    build: ./backend
    ports:
      - '5001:5001'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/db?schema=public
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5001

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    healthcheck:
    test: ['CMD-SHELL', 'pg_isready -U postgres']
    interval: 10s
    timeout: 5s
    retries: 5
